name: Push or Pull demo
on:
  push:
    branches:
      - example-branch/*
  pull_request:
    branches:
      - main
    types:
      - opened
      - synchronize
      - reopened
jobs:
  push-job:
    runs-on: ubuntu-24.04
    steps:
      - name: Say Hello
        run: echo "Push triggered in this workflow"
      - name: Show Branch
        run: echo "$GITHUB_REF_NAME"
      - name: Show event name
        run: echo "Event: $GITHUB_EVENT_NAME"
